# serverless.yml
# https://github.com/danielcondemarin/serverless-next.js

feBoilerplateClient:
  component: "@sls-next/serverless-component@3.1.0"
  inputs:
    useServerlessTraceTarget: true
    cloudfront:
      waitBeforeInvalidate: false
    bucketName: "boilerplate-client-qa"
    bucketRegion: "us-east-1"
    description: "Boilerplate Client for QA env, NextJS Lambda@Edge for Cloudfront distribution"
    name:
      defaultLambda: feBoilerplateClientDefaultQA
      imageLambda: feBoilerplateClientImageQA
    timeout:
      defaultLambda: 30
      imageLambda: 15
    memory:
      defaultLambda: 1024
      imageLambda: 2048
    publicDirectoryCache:
      value: public, max-age=31536000, must-revalidate
      test: /\.(gif|jpe?g|jp2|tiff|png|webp|bmp|svg|ico|json|woff2)$/i